### ISSUE TITLE
Wrapper not working for Task<IActionResult>

### ISSUE THREAD

**Issue by mmarquesbr** [proudmonkey/RESTApiResponseWrapper.Core#10]
When our method returns a Task<IActionResult>, the wrapper fails and always returns null as value.

**Comment by proudmonkey** [comment]
That's interesting. Instead of returning `Task<IActionResult>`, you can try returning a Task with the actual type. For example, `Task<YourModel>`

**Comment by Kum4r4n** [comment]
@proudmonkey  can you explain that, i had same problem with IActionResult, returning null value

**Comment by proudmonkey** [comment]
Hi @Kum4r4n,

I'm saying is that, Instead of returning `Task<IActionResult>`, you can try returning a Task with the actual type. For example, `Task<YourModel>`

**Comment by Kum4r4n** [comment]
@proudmonkey Thanks for replay to me, but the problem is I returning Task<IActionResult> , But i got return value as unsupported structure json value. 

These are my code 
![LKNLKN](https://user-images.githubusercontent.com/31638942/59452816-30cda700-8e2c-11e9-82b6-4409d0922fb1.PNG)

Task<Token> in here Token is my model name 

and This is the response body
![JJJJJ](https://user-images.githubusercontent.com/31638942/59452884-55c21a00-8e2c-11e9-8c20-436fe589a87a.PNG)

How can i fix that ?

**Comment by proudmonkey** [comment]
Hi @Kum4r4n ,

Try to return the APIResponse object and pass the tokenResult value within that object. For example:

`
public async Task<APIResponse> Login([FromBody]LoginModel userParam)
{
     // your code here

     Token  tokenResult = new Token()
     {
             token = jwtToken,
             refreshtoken = refreshToken
     };

    return new APIResponse(200, "Login Successful", tokenResult);
}
`

**Comment by Kum4r4n** [comment]
Oh thanks.   Is that apiResponse support to JsonApiSpecs ?

**Comment by proudmonkey** [comment]
>  Is that apiResponse support to JsonApiSpecs ?

I'm not familiar with that, unfortunately :(
