### ISSUE TITLE
APIResponseRequestLogginMiddleware produces invalid JSON response

### ISSUE THREAD

**Issue by nstohler** [proudmonkey/RESTApiResponseWrapper.Core#12]
When I have a decimal in my dto, the middleware produces invalid JSON. I've described the behavior here:

https://github.com/enkodellc/blazorboilerplate/issues/25

**Comment by proudmonkey** [comment]
@nstohler that's interesting. Thanks for letting me know. I'll check this and get back to you for an update.

**Comment by proudmonkey** [comment]
@nstohler I've pushed an initial update for this. I will finalized the update once ASP.NET Core 3 is released. Try the code and let me know the result. Thanks!

**Comment by nstohler** [comment]
Thanks, I will try it at a later stage. I'm currently using decimals only on the server side, converting them to strings for the client side

**Comment by nasserkhalifa** [comment]
Hey,
The problem is with the response content length that remains the same length of the original body length, so the browser will take that length and try to parse it which causes the problem.
I've just added this code :
context.Response.ContentLength = responseBody.Length;
at the beginning of finally scope
